language: python
python:
- '3.6'
- '3.7'
- '3.8'
branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+.*$/
script:
  - pytest --cov=./
install:
    - pip install -r requirements.txt
    - pip install -e .
after_success:
    - bash <(curl -s https://codecov.io/bash)
